### PR TITLE
Update raster attributes if downsample is not 1

### LINKED ISSUE #131: dowsample does not update raster attributes
```
from geoutils import georaster as gr
from geoutils import datasets
img = gr.Raster(datasets.get_path('landsat_B4'))
print(img.width, img.height, img.res)
```
800 655 (30.0, 30.0)

```
img = gr.Raster(datasets.get_path('landsat_B4'), downsample=2)
print(img.width, img.height, img.res)
```
800 655 (30.0, 30.0)

### PR DESCRIPTION
**Pull request by adehecq**
Resolves #131

### CODE REVIEW

**Review by atedstone — APPROVED** [review]

**Comment by atedstone** [comment]
Looks good to me. Feel free to merge :)

**Comment by adehecq** [comment]
Actually, some methods relying on rasterio's functionalities like xy2ij will still work incorrectly. I need to check if that can be updated.

**Comment by rhugonnet** [comment]
> Actually, some methods relying on rasterio's functionalities like xy2ij will still work incorrectly. I need to check if that can be updated.

As Erik said, might be worth opening an issue in rasterio on the default behaviour of `.index()`. I'll do that next week.

**Comment by adehecq** [comment]
> > Actually, some methods relying on rasterio's functionalities like xy2ij will still work incorrectly. I need to check if that can be updated.
> 
> As Erik said, might be worth opening an issue in rasterio on the default behaviour of `.index()`. I'll do that next week.

No, it was another issue. Until now I was updating self's attributes, but not self.ds attributes so rio's functionalities where not working correctly. I just fixed that hopefully.

**Pull request merged**
