### PR TITLE
environment.yml file for a geoutils environment

### PR DESCRIPTION
**Pull request by elischwat**
I had trouble getting things started today due to lack of an environment file. This environment (and the updated readme instructions) got the tests running for me. I tested on Mac and Linux.

We can update the github actions to using the environment.yml if desired.

### CODE REVIEW

**Comment by adehecq** [comment]
So if I understand correctly, the requirement.txt file is not sufficient to get things running?

**Comment by atedstone** [comment]
Checking locally at the moment.

**Comment by elischwat** [comment]
I meant for this PR to also remove the requirements.txt. Adding that change now...

**Comment by atedstone** [comment]
I'd probably leave requirements.txt in place for non-conda folks?

**Comment by atedstone** [comment]
Alright, I'll try to get rid of the need for requirements.txt. Need to fix the build action and the RTD stuff first.

**Review by atedstone — APPROVED** [review]

**Pull request merged**
