### PR TITLE
Simplify import statements

### PR DESCRIPTION
**Pull request by erikmannerfelt**
See the rationale in #141.

Example:
```python
import geoutils as gu

r = gu.Raster("...")
v = gu.Vector("...")
img = gu.SatelliteImage("...")
```

### CODE REVIEW

**Review by rhugonnet — APPROVED** [review]
Perfect :)

**Comment by rhugonnet** [comment]
Should we update this in all tests/package imports as well? It would improve readability

**Comment by erikmannerfelt** [comment]
@rhugonnet , that sounds good! Should we do it here or in a separate PR?

**Comment by rhugonnet** [comment]
> @rhugonnet , that sounds good! Should we do it here or in a separate PR?

If you have the time now here is good. Otherwise you can merge and we'll do in another PR (and need to open issue to not forget about it).

**Comment by atedstone** [comment]
This is excellent, thanks for the initiative. Let's get the documentation and test suite updated first before we merge this PR - @erikmannerfelt , if you'd like to do it then feel free, else I  can probably find some time in the next couple of days.

**Comment by erikmannerfelt** [comment]
@atedstone, thank you! Unfortunately I've already merged since this was approved. We should make a new PR I guess for the tests and docs. I am currently on a project in xdem, but I can find time sometime soon to fix it. If you have time, please go ahead before me!

**Pull request merged**
