### PR TITLE
Homogenize API arguments

### PR DESCRIPTION
**Pull request by atedstone**
**This PR causes breaking changes to API**

Resolves the rest of #432. 

- [x] Remove `dst_`
- [x] Replace `rst` with raster
- [x] `grid_size` to `size`
- [x] The various forms of sample (see below)
- [x]  Always use `points`, never `pts`

## Grammar of sampling

This PR proposes to regularise the grammar around the word sample and its derivatives.
- When the intention is to return a (random) sample, the term `sample` is used. Previously, `subset` or `subsample` were both used to denote this purpose.
- `downsample` or `upsample` defines a change in a Raster's resolution.  The more generic term is `resample`, but the use of a specific direction is preferred. Try not to use `resample` as this has connotations of towards `reproject`.
- The terms `subset` and `subsample` refer to an contiguous portion of data (e.g. an `x*y` window of a `Raster`, specific bands of a `Raster`, or `row n...row m` of a `Vector`), without a change in resolution. I am regularising to `subset`.

### CODE REVIEW

**Review by rhugonnet — APPROVED** [review]
Thanks @atedstone, this is great!! I didn't find anything to comment on in the code changes.

I like the homogenization to `sample` and differentiation with `subset`! :smile:  
It looks like `subset` is used only in `split_bands`, we could even rename into something specific to that function like `bands` to avoid any kind of confusion?

**Review by adehecq — APPROVED** [review]
Nice work !
As discussed on slack, I find that removing the `dst_` prefix everywhere makes sense from a user/API point of view, but it may be a bit less easy to read the code. We'll see!
I find that `size` is not clear enough. I would favor `grid_size` to clarify that we're talking about the dimensions of the array. But we can revert in a future PR if we all agree.

**Comment by adehecq** [comment]
> It looks like `subset` is used only in `split_bands`, we could even rename into something specific to that function like `bands` to avoid any kind of confusion?

For consistency, we could use the same terminology as in `load` which is `indexes`. Although I'm not a huge fan of that term, I always forget the name...

**Comment by atedstone** [comment]
I also don't find `indexes` that intuitive. From the xarray side of life, index can be along any dimension. How about the keyword `band/bands` instead, for both `load()` and `split_bands()`?

**Comment by adehecq** [comment]
> I also don't find `indexes` that intuitive. From the xarray side of life, index can be along any dimension. How about the keyword `band/bands` instead, for both `load()` and `split_bands()`?

I would be fine with `bands`. But this would just be undoing what was done in a previous PR: https://github.com/GlacioHack/geoutils/pull/346. Any thoughts @rhugonnet ?

**Comment by rhugonnet** [comment]
+1 for `grid_size` and for `bands`!

**Pull request merged**
