### PR TITLE
Plotting

### PR DESCRIPTION
**Pull request by atedstone**
Add a .show() method.

### CODE REVIEW

**Comment by atedstone** [comment]
n.b. there's only one commit in this PR to look at, 30484cf. I branched from #36 .

**Review by adehecq — COMMENTED** [review]
I'm curious how rshow works underneath. Since the rasterio ds does not have any data associated with it, does it mean that rshow loads the data again in memory?

**Comment by atedstone** [comment]
Interesting point. I'll look into this. Sometimes the rasterio ds does actually have data associated with it, most notably if using the classmethod `from_array`.

**Review by rhugonnet — APPROVED** [review]
Looks good. Seems some package names were already changed by a previous PR, will see if there is conflict when merging.

**Comment by adehecq** [comment]
@rhugonnet have you looked at my earlier comment? I'm concerned that using rasterio's plotting function might load the data a second time, which is not ideal for large data set...

**Comment by rhugonnet** [comment]
> @rhugonnet have you looked at my earlier comment? I'm concerned that using rasterio's plotting function might load the data a second time, which is not ideal for large data set...

So should we plot using something else instead? Cartopy?

**Comment by rhugonnet** [comment]
I think the idea for now is to have some plotting capability in order to rapidly check the function outputs and move forward. I can  open an issue on this and works towards a better solution?

**Comment by atedstone** [comment]
I'm inclined to agree with @rhugonnet , we can change the code underneath the plot method later if/when we find there to be a problem.

**Comment by rhugonnet** [comment]
Thanks Amaury, I have linked an issue from your comment to check the data loading of rio plotting.

**Comment by adehecq** [comment]
Sounds good!

**Pull request merged**
