### PR TITLE
Satellite image subclass + test functions, with metadata parsing (instrument, date, tile) from filename and manipulating of classic tile naming conventions

### PR DESCRIPTION
**Pull request by rhugonnet**
_This PR is unavoidably associated to changes in the other PR (was necessary, mostly on the organisation of classes + of the related tests with pytest), so it is branched from the "romain" branch and the early commits correspond to those in the other PR... I could merge the "satimg" into the "romain" branch but that would make things more complicated for partitioning changes? Maybe if we accept the other PR, the files changes in this one will be more readable? (not that familiar with those GitHub "best practices")_

**Added satimg.py with the SatelliteImage class, with super-class Raster**. A SatelliteImage object has attributes related to metadata that cannot be written/passed through a Raster format (e.g., datetime, tile name, instrument, satellite, etc...).
Introduced: 
- methods to parse basic metadata from filename
- methods to manipulate tile naming convention and coordinates
To add in the future:
- link instrument specific methods to parse metadata from related file like a .xml or other (existing routines for Landsat, ASTER, etc...)
- derive extent from the tile name/size/projection? first need to add related methods in geovector.py
- DEM will be a subclass of SatelliteImage

**Added related test functions with pytest** (same on the other PR for georaster). Very useful once you know how to make it work. Took some tweaking, but now all is running 100% OK :)

Open to suggestions for naming (SatImg? @iamdonovan?)

### CODE REVIEW

**Comment by atedstone** [comment]
Waiting on #56 before checking this

**Review by adehecq — APPROVED** [review]

**Comment by atedstone** [comment]
96c0947 fixed some merge conflicts that would have appeared, and also forced the build process to start now that it is required for the PR to be merged

**Comment by atedstone** [comment]
@rhugonnet , one test in the satimg test suite is failing. check it out using the 'Details' option above

**Comment by rhugonnet** [comment]
> @rhugonnet , one test in the satimg test suite is failing. check it out using the 'Details' option above

on it! Friday meeting is almost over

**Pull request merged**
