### PR TITLE
Fix for issue #409 and #407

### PR DESCRIPTION
**Pull request by adehecq**
- solves #407 
- solves #409

### CODE REVIEW

**Comment by rhugonnet** [comment]
A bit afraid that the plotting changes will break examples in the documentation, as this is why this code was modified in the first place. Before merging, we should check how the documentation renders on your fork @adehecq (you need to go to readthedocs and build the branch on your fork, can give more details if you haven't done that before)

**Comment by adehecq** [comment]
Right now, I fail building the documentation on readthedocs for this branch... But this does not seem to be related to the change to plots are undoing it did not solve the issue.

**Comment by rhugonnet** [comment]
Strange, because the documentation of the `main` branch is still passing (restarted a build today to try): https://readthedocs.org/projects/geoutils/builds/22932914/

**Comment by adehecq** [comment]
Ok, now the doc compiled (I don't know why it was not working before but now it does...).
Here is the link: https://geoutils-adehecq.readthedocs.io/en/amaury_fixes/index.html.
@rhugonnet, where did you expect the changes to break the doc? I looked at a few figures and they appeared as expected.

**Comment by rhugonnet** [comment]
Indeed, I couldn't find any figure that looked different! :partying_face:
But let's remember to check every page of the doc before we release a `0.1` after the hackathon!

**Review by rhugonnet — APPROVED** [review]
Great, thanks for looking into this!

**Pull request merged**
