### PR TITLE
Create a separate dataset folder and function to access it

### PR DESCRIPTION
**Pull request by adehecq**
@rhugonnet @atedstone 
What do you think of this to access the demo data? It's similar to geopandas. The data path can be found with:
```
from geoutils import datasets
datasets.get_path("landsat_B4")
```
and the list of available datasets
`datasets.datasets`

### CODE REVIEW

**Comment by adehecq** [comment]
If that works, I'll update the tests accordingly.

**Comment by rhugonnet** [comment]
looks good indeed! hope it works without the circular import issue

**Review by atedstone — APPROVED** [review]
this looks good to me

**Comment by adehecq** [comment]
Try using relative paths in the tests so that it doesn't fail in CI tests.

**Comment by adehecq** [comment]
For the record: the issue with failed tests on the datasets is that datasets is a package (folder with init file) rather than module. Packages must be defined in the seup.py file.
Additionally, the data files must be provided in the setup.py file to be copied when using `pip install .`.

**Pull request merged**
