### PR TITLE
Add number of bands and datatypes to info(). Fix #63

### LINKED ISSUE #63: Add number of bands to info()

### PR DESCRIPTION
**Pull request by adehecq**

### CODE REVIEW

**Comment by rhugonnet** [comment]
rio doesn't have those lines in it's "info", so I'm surprised that the test_info() check is still passing:
```
#check summary matches that of RIO
        assert print(r) == print(r.info())
```
do you know why?

**Comment by adehecq** [comment]
in your example, r.info() is not rasterio's info, it's our info!
I don't think rasterio has something similar, does it?

**Comment by rhugonnet** [comment]
Oh, so the "print" function on an object automatically calls the .info() function within its class?! that's pretty neat, I didn't know

**Comment by adehecq** [comment]
It's because of this line: https://github.com/GlacioHack/GeoUtils/blob/951f78cb8e3f7a6be284bdbe0415c139688b3a81/geoutils/georaster.py#L177

**Comment by adehecq** [comment]
Can you accept the PR?

**Review by rhugonnet — APPROVED** [review]

**Pull request merged**
