### PR TITLE
Attempt to fix issue with doc building on Mac/Windows

### PR DESCRIPTION
**Pull request by adehecq**
Attempts to fix an issue only referenced on xdem: https://github.com/GlacioHack/xdem/issues/316.

- Fix an issue of shapely backward compatibility in one of the examples 
- Re-enable `test_doc.py` for Mac -> The test now passes ! 🥳 (I'm not sure if it's related to my change or it was fixed earlier). 
- Remove the fixed version for pydata-sphinx-theme which was causing a bug with the logo (see #351)
- Doc was also building on Windows, until the new CLI doc section (#418)

Raised issue #442 for the Windows problem.

### CODE REVIEW

**Comment by adehecq** [comment]
Should I disable tests for Windows then? Or we should have someone test it locally on a Windows to understand the issue...

**Comment by rhugonnet** [comment]
Talk about a useless message, `Undefined error`... :sweat: 

It also says "Theme error" right next to it.
We could try unfixing the `pydata-sphinx-theme` version that had to be fixed to build correctly with `sphinx-book-theme`: https://github.com/GlacioHack/geoutils/blob/main/dev-environment.yml#L32. See issue: https://github.com/GlacioHack/geoutils/pull/413.

We can unfix it now because Sphinx book theme just released a new version that works with the new Pydata theme: https://github.com/executablebooks/sphinx-book-theme/releases, and apparently fixes a lot of bugs.

If the rendering is good, it would also solve issue https://github.com/GlacioHack/xdem/issues/452 once mirrored in xDEM! :slightly_smiling_face:

**Comment by rhugonnet** [comment]
And otherwise yes, we should probably not lose time on this mysterious error and just skip Windows

**Comment by adehecq** [comment]
@rhugonnet, the test does not fail on Windows anymore after unfixing the `sphinx-book-theme` !! 🥳 
You can check the new doc here: https://geoutils-adehecq.readthedocs.io
I didn't see any issue. The theme is slightly different than the previous one, but it looks fine.

**Review by rhugonnet — APPROVED** [review]
Amazing!! We're solving a lot of old problems :)

**Comment by adehecq** [comment]
Pfff, after merging with the main branch, the doc build fails again on Windows. It seems related to the new CLI section. The path to the script `geoviewer.py` is not found on windows. This may be a sign that actually, `geoviewer.py` is not working on Windows?

**Pull request merged**
