### PR TITLE
Remove checks on non-existent variables

### LINKED ISSUE #38: In Raster.reproject, opt_npx and opt_res undefined
At line https://github.com/GlacioHack/GeoUtils/blob/45d67067fe4568a5f6196e81a452b92d657eb7b2/geoutils/georaster.py#L392

### PR DESCRIPTION
**Pull request by atedstone**
Fixes #38 .

### CODE REVIEW

**Comment by atedstone** [comment]
I ran a couple of quick test cases as follows:

```
from geoutils import georaster
im = georaster.Raster('LE71400412000304SGS00_B4_crop.TIF')
print(im.reproject(3413))
print(im.reproject(3413, dst_size=(100,100)))
print(im.reproject(3413, dst_res=100))
```

Still need to build some unit tests...

**Comment by adehecq** [comment]
I don't think it works yet. If you set dst_bounds, then the method returns None.

**Comment by atedstone** [comment]
@adehecq do you have a test case for this? (image file and the bounds)

**Review by adehecq — APPROVED** [review]
Ok for this specific error, but will add new issues for the subsequent errors.

**Pull request merged**
