### PR TITLE
Add `np.abs` and `np.absolute` to supported NumPy array functions in `Raster`

### PR DESCRIPTION
**Pull request by rhugonnet**
Helps on https://github.com/GlacioHack/xdem/issues/404

### CODE REVIEW

**Review by erikmannerfelt — APPROVED** [review]
Extravagant!

**Comment by erikmannerfelt** [comment]
Oh by the way, why are there multiple lists like that? Not for this PR, but it could be simplified to just one list, and one comprehension perhaps that adds "nan" suffixes to some of them.

**Comment by rhugonnet** [comment]
It's because they are from different NumPy submodules (logical: https://numpy.org/doc/stable/reference/routines.logic.html, linear algebra: https://numpy.org/doc/stable/reference/routines.linalg.html, mathematical functions: https://numpy.org/doc/stable/reference/routines.math.html, etc...) and only a few of them have a "NaN" version.

I could add a comment with the link to NumPy each time to clarify?

**Comment by rhugonnet** [comment]
Comments added to make the list organization clear!

**Pull request merged**
