### PR TITLE
Renaming

### PR DESCRIPTION
**Pull request by atedstone**
In all code, GeoUtils is now geoutils, and module names have had the hyphens removed. This makes the package more inline with the likes of geopandas, xarray etc - fewer keystrokes needed.

### CODE REVIEW

**Review by iamdonovan — APPROVED** [review]

**Review by adehecq — COMMENTED** [review]
While we're talking naming conventions, I quite liked the georaster, geovector compared to rastertools/vectortools. It could be a time to change it, but I have no strong preference for it.

**Review by adehecq — APPROVED** [review]

**Comment by atedstone** [comment]
speak now or forever hold your peace...........I've no strong preference either, but this is probably the best and/or near-last time to make such a large change, before we starting using the package properly.

**Comment by iamdonovan** [comment]
I still don't have strong preferences either way. I use things like "X_tools" because I lack imagination, not because I have strong feelings about it. :)

**Comment by adehecq** [comment]
Then I vote for georaster/geovector because 1) it's more explicit that we're dealing with georeferenced data and 2) I almost don't need to update my scripts ;-)

**Comment by atedstone** [comment]
your wish is my command...

**Comment by atedstone** [comment]
I think that I've made all necessary changes. Merging and closing this PR but do keep an eye out for problems, this is where we need the fabled testing framework!

**Pull request merged**
